"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";

function cleanReport(text: string): string {
  const shouldDropLine = (trimmed: string): boolean => {
    if (trimmed.includes("Disclaimer: This report was generated by AI")) return true;
    if (trimmed.includes("This report was generated by AI")) return true;
    if (trimmed.includes("Always verify with live sources such as CoinMarketCap")) return true;
    if (trimmed.includes("verify with live sources such as CoinMarketCap")) return true;
    if (trimmed.includes("Financial figures and statistics may be based on training data")) {
      return true;
    }
    if (trimmed.includes("not reflect current values")) return true;
    if (trimmed.includes("verify with CoinMarketCap, CoinGecko, Bloomberg, or Reuters")) {
      return true;
    }
    return false;
  };

  return text
    .split("\n")
    .map((line) =>
      line.startsWith("> ") ? line.slice(2) : line.startsWith(">") ? line.slice(1) : line,
    )
    .filter((line) => !shouldDropLine(line.trim()))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function normalizeReportMarkdown(text: string): string {
  const sectionHeadings = [
    "Executive Summary",
    "Key Facts",
    "Recent Developments",
    "Data & Statistics",
    "Analysis",
    "Conclusion",
  ];

  let normalized = text;

  for (const heading of sectionHeadings) {
    const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    normalized = normalized.replace(
      new RegExp(`^(#{1,6}\\s+${escaped})\\s*[:\\-]\\s+(.+)$`, "gmi"),
      "$1\n\n$2",
    );
    normalized = normalized.replace(
      new RegExp(`^(#{1,6}\\s+${escaped})\\s+(.+)$`, "gmi"),
      "$1\n\n$2",
    );
  }

  normalized = normalized.replace(
    /^(#{1,6}\s+.+)\n(?!\n|#{1,6}\s|\- |\* |\d+\. |\| )(.*\S.*)$/gim,
    "$1\n\n$2",
  );

  return normalized.replace(/\n{3,}/g, "\n\n").trim();
}

function countWords(text: string): number {
  return text.split(/\s+/).filter(Boolean).length;
}

export function Report({ markdown }: { markdown?: string | null }) {
  const [copied, setCopied] = useState(false);

  if (!markdown) {
    return (
      <div className="border-t border-gold/10 pt-8">
        <div className="flex min-h-[180px] items-center justify-center rounded-2xl border border-gold/16 bg-gold/[0.03] px-6 text-center">
          <span className="text-base font-medium text-white/72">
            Run the pipeline to generate the report.
          </span>
        </div>
      </div>
    );
  }

  const cleaned = normalizeReportMarkdown(cleanReport(markdown));
  const wordCount = countWords(cleaned);
  const readTime = Math.max(1, Math.round(wordCount / 180));

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(cleaned);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
    }
  };

  return (
    <div className="flex h-full flex-col">
      <div className="mb-12 flex items-center justify-between border-b border-white/5 pb-6">
        <div className="flex gap-8 text-[10px] uppercase tracking-[0.2em] text-white/40">
          <span>{wordCount} Words</span>
          <span>{readTime} Min Read</span>
        </div>
        <button
          type="button"
          onClick={handleCopy}
          className="text-[10px] uppercase tracking-[0.2em] text-gold/70 transition-colors hover:text-gold"
        >
          {copied ? "Copied to Clipboard" : "Copy Content"}
        </button>
      </div>

      <article className="max-h-[800px] overflow-auto pr-4 text-white lg:pr-12">
        <div className="max-w-prose break-words">
          <ReactMarkdown
            components={{
              h1: ({ children }) => (
                <h1 className="mb-10 text-4xl font-light tracking-tight text-gold">
                  {children}
                </h1>
              ),
              h2: ({ children }) => (
                <h2 className="mt-14 mb-6 text-xl font-light tracking-wide text-gold">
                  {children}
                </h2>
              ),
              h3: ({ children }) => (
                <h3 className="mt-10 mb-4 text-lg font-light tracking-wide text-gold/92">
                  {children}
                </h3>
              ),
              p: ({ children }) => (
                <p className="mb-8 text-base font-light leading-loose text-white/88">
                  {children}
                </p>
              ),
              ul: ({ children }) => (
                <ul className="mb-8 list-none space-y-3 pl-0 text-base font-light leading-loose text-white/88">
                  {children}
                </ul>
              ),
              ol: ({ children }) => (
                <ol className="mb-8 list-decimal space-y-3 pl-5 text-base font-light leading-loose text-white/88">
                  {children}
                </ol>
              ),
              li: ({ children }) => (
                <li className="relative pl-6 text-white/88 before:absolute before:left-0 before:top-3 before:h-[1px] before:w-3 before:bg-gold/50">
                  {children}
                </li>
              ),
              blockquote: ({ children }) => (
                <blockquote className="my-10 border-l border-gold/30 pl-8 text-lg font-light italic leading-loose text-white/88">
                  {children}
                </blockquote>
              ),
              code: ({ children }) => (
                <code className="rounded bg-white/6 px-1.5 py-0.5 font-mono text-[13px] text-white/92">
                  {children}
                </code>
              ),
              pre: ({ children }) => (
                <pre className="my-10 overflow-x-auto rounded-2xl border border-white/8 bg-white/[0.02] px-5 py-6 font-mono text-[13px] leading-relaxed text-white/84">
                  {children}
                </pre>
              ),
              a: ({ children, href }) => (
                <a
                  href={href}
                  target="_blank"
                  rel="noreferrer"
                  className="border-b border-gold/30 pb-0.5 text-white/92 transition-colors hover:border-gold hover:text-gold"
                >
                  {children}
                </a>
              ),
              strong: ({ children }) => (
                <strong className="font-medium text-white">{children}</strong>
              ),
              hr: () => <hr className="my-14 border-white/5" />,
            }}
          >
            {cleaned}
          </ReactMarkdown>
        </div>
      </article>
    </div>
  );
}
